# Licensed Materials - Property of IBM
# (C) Copyright IBM Corporation 2016, 2019. All Rights Reserved.
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "helm-api-v2"
  annotations:
    kubernetes.io/ingress.class: "ibm-icp-management"
    icp.management.ibm.com/authz-type: "rbac"
    icp.management.ibm.com/rewrite-target: "/api/v2"
    icp.management.ibm.com/proxy-connect-timeout: "60"
    icp.management.ibm.com/proxy-read-timeout: "300"
    icp.management.ibm.com/proxy-send-timeout: "300"
  labels:
    app: "helm-api"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
    app.kubernetes.io/name: "helm-api"
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  rules:
  - http:
      paths:
      - path: /helm-api/api/v2/
        backend:
          serviceName: "{{ .Values.helmapi.service.name }}"
          servicePort: {{ .Values.helmapi.service.port }}
            