apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "operator.ibm.com/v1alpha1",
          "kind": "HelmApi",
          "metadata": {
            "name": "example-helmapi"
          },
          "spec": {
            "arch": "",
            "auditService": {
              "config": {
                "enabled": true
              },
              "image": {
                "pullPolicy": "IfNotPresent",
                "repository": "quay.io/opencloudio/icp-helm-repo",
                "tag": "3.3.1"
              },
              "name": "icp-audit-service"
            },
            "helmapi": {
              "env": {
                "CLUSTER_CA_DOMAIN": "mycluster.icp",
                "CLUSTER_PORT": 8443,
                "DBHOST": "mongodb",
                "DBPORT": "27017",
                "HTTPS_PROXY": "",
                "HTTP_PROXY": "",
                "ISICP": true,
                "LOAD_ROUTES": "API",
                "MONGO_ISSSL": true,
                "MONGO_SSL_CA": "/certs/mongodb-ca/tls.crt",
                "MONGO_SSL_CERT": "/certs/mongodb-client/tls.crt",
                "MONGO_SSL_KEY": "/certs/mongodb-client/tls.key",
                "NO_PROXY": "mycluster.icp,mongodb,platform-identity-provider,icp-management-ingress, iam-pap,localhost,127.0.0.1",
                "PROXY_EXTERNAL_ADDR": "proxy_external_address",
                "PROXY_ROUTE": "helm-api",
                "SET_TLS": "true",
                "WLP_REDIRECT_URL": "http://localhost:3000/auth/liberty/callback"
              },
              "image": {
                "name": "helmapi",
                "pullPolicy": "IfNotPresent",
                "repository": "quay.io/opencloudio/icp-helm-api",
                "tag": "3.3.0"
              },
              "resources": {
                "limits": {
                  "cpu": "300m",
                  "memory": "400Mi"
                },
                "requests": {
                  "cpu": "200m",
                  "memory": "300Mi"
                }
              },
              "secretKeyRef": {
                "clientIdSecretKey": "WLP_CLIENT_ID",
                "clientIdSecretName": "platform-oidc-credentials",
                "clientSecretSecretKey": "WLP_CLIENT_SECRET",
                "clientSecretSecretName": "platform-oidc-credentials",
                "dbSecretName": "icp-mongodb-admin",
                "dbSecretPassKey": "password",
                "dbSecretUserKey": "user"
              },
              "service": {
                "name": "helm-api",
                "port": 3000,
                "portName": "helmapiport"
              },
              "sharedassets": {
                "name": "sharedassets",
                "path": "/usr/src/app/assets"
              },
              "volumeMounts": {
                "helmApiCertsMountPath": "/etc/certs",
                "helmApiCertsName": "helmapi-certs",
                "mongoCaMountPath": "/certs/mongodb-ca",
                "mongoCaName": "mongodb-ca-cert",
                "mongoClientCertMountPath": "/certs/mongodb-client",
                "mongoClientCertName": "mongodb-client-cert"
              }
            },
            "nodeSelector": {
              "master": "true"
            },
            "replicaCount": 1,
            "rudder": {
              "env": {
                "RUDDER_CLIENT_CERTS": "/etc/certs",
                "RUDDER_TILLER_ADDRESS": "tiller-deploy.kube-system:44134",
                "USE_TLS": "true"
              },
              "image": {
                "name": "rudder",
                "pullPolicy": "IfNotPresent",
                "repository": "quay.io/opencloudio/icp-helm-rudder",
                "tag": "3.2.2"
              },
              "ports": {
                "containerPort": 5000,
                "containerPortName": "p5000",
                "protocol": "TCP"
              },
              "resources": {
                "limits": {
                  "cpu": "150m",
                  "memory": "128Mi"
                },
                "requests": {
                  "cpu": "100m",
                  "memory": "128Mi"
                }
              },
              "volumeMounts": {
                "rudderCacheMountPath": "/opt/rudder/cache",
                "rudderCacheName": "rudder-cache",
                "rudderCertsMountPath": "/etc/certs",
                "rudderCertsName": "rudder-certs"
              }
            },
            "runAsUser": 65534,
            "tolerations": [
              {
                "effect": "NoSchedule",
                "key": "dedicated",
                "operator": "Exists"
              },
              {
                "key": "CriticalAddonsOnly",
                "operator": "Exists"
              }
            ],
            "volumes": {
              "helmApiCertsName": "helmapi-certs",
              "helmApiCertsSecretName": "helmapi-secret",
              "mongoCaCertName": "mongodb-ca-cert",
              "mongoCaCertSecretName": "cluster-ca-cert",
              "mongoClientCertName": "mongodb-client-cert",
              "mongoClientCertSecretName": "icp-mongodb-client-cert",
              "rudderCertsName": "rudder-certs",
              "rudderCertsSecretName": "rudder-secret"
            }
          }
        }
      ]
    capabilities: Basic Install
  name: ibm-helm-api-operator.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Helmapi CRD for the IBM helm repo chart.
      displayName: IBM Helm api Operator
      kind: HelmApi
      name: helmapis.operator.ibm.com
      version: v1alpha1
  description: IBM Helm api Operator provides helm repo service
  displayName: Ibm Helm Api Operator
  install:
    spec:
      deployments:
      - name: ibm-helm-api-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: ibm-helm-api-operator
          strategy: {}
          template:
            metadata:
              labels:
                name: ibm-helm-api-operator
            spec:
              containers:
              - env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['olm.targetNamespaces']
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: ibm-helm-api-operator
                image: quay.io/opencloudio/ibm-helm-api-operator
                imagePullPolicy: Always
                name: ibm-helm-api-operator
                resources: {}
              serviceAccountName: ibm-helm-api-operator
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - pods
          - services
          - services/finalizers
          - endpoints
          - persistentvolumeclaims
          - events
          - configmaps
          - secrets
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - namespaces
          verbs:
          - get
        - apiGroups:
          - ""
          resources:
          - configmaps
          - secrets
          verbs:
          - '*'
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - get
          - create
        - apiGroups:
          - apps
          resourceNames:
          - ibm-helm-api-operator
          resources:
          - deployments/finalizers
          verbs:
          - update
        - apiGroups:
          - ""
          resources:
          - pods
          verbs:
          - get
        - apiGroups:
          - apps
          resources:
          - replicasets
          - deployments
          verbs:
          - get
        - apiGroups:
          - charts.helm.k8s.io
          resources:
          - '*'
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        serviceAccountName: ibm-helm-api-operator
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - IBM
  - Cloud
  maintainers:
  - email: support@ibm.com
    name: IBM Support
  maturity: alpha
    name: IBM
  replaces: ibm-helm-api-operator.v0.0.0
  version: 0.0.1
