# Licensed Materials - Property of IBM
# (C) Copyright IBM Corporation 2016, 2019. All Rights Reserved.
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

## Metadata for <PRODUCTNAME> configuration
## This metadata is used to drive IBM Cloud Private UI for configuration of the Helm chart installation

replicaCount:
  __metadata:
    label: "Replica count"
    description: "How many pods to run simultaneously"
    type: "number"
    immutable: true
    required: true
nodeSelector:
  __metadata:
    label: "Node selector criteria"
    description: "Criteria for selecting node to run on"
    hidden: true
  master:
    __metadata:
      label: "Master node selector"
      description: "Determines whether the component is scheduled on the master node"
      type: string
      immutable: true
      hidden: true
tolerations:
  __metadata:
    label: "Tolerations"
    description: "Pod tolerations for assigning to nodes with matching taints"
    required: true
    
arch:
  __metadata:
    label: "Node architecture"
    description: "Node architecture to deploy to. The helm chart will try to detect the architecture based on the master node."
    type: "string"
    immutable: false
    required: false
    options:
      - label: "amd64"
        value: "amd64"
      - label: "ppc64le"
        value: "ppc64le"
      - label: "s390x"
        value: "s390x"

runAsUser:
  __metadata:
    label: "Run as User"
    description: "What user to run as"
    type: "string"
    immutable: false
    required: false

helmapi:
  __metadata:
    label: "API core component"
    description: "REST api component for helm charts and releases"
    hidden: true
  image:
    name:
      __metadata:
        label: "Image name"
        description: "Docker image name"
        type: "string"
        required: true
    repository:
      __metadata:
        label: "Repository"
        description: "Docker image location"
        type: "string"
        required: true
    tag:
      __metadata:
        label: "Tag"
        description: "Docker image tag"
        type: "string"
        required: false
    pullPolicy:
      __metadata:
        label: "Image pull policy"
        description: "Docker image pull policy"
        type: "string"
        required: true      
        options:
        - label: "Always"
          value: "Always"
        - label: "Never"
          value: "Never"
        - label: "IfNotPresent"
          value: "IfNotPresent"
  volumeMounts:
    mongoCaName:
      __metadata:
        label: "Mongo CA name"
        description: "helmapi mongoDB CA mount name"
        type: "string"
    mongoCaMountPath:
      __metadata:
        label: "Mongo CA mount"
        description: "helmapi mongoDB CA mount path"
        type: "string"
    mongoClientCertName:
      __metadata:
        label: "Mongo Cert name"
        description: "helmapi mongoDB client cert mount name"
        type: "string"
    mongoClientCertMountPath:
      __metadata:
        label: "Mongo Cert mount"
        description: "helmapi mongoDB client cert mount path"
        type: "string"
    helmApiCertsName:
      __metadata:
        label: "Helmapi Cert name"
        description: "helmapi certs mount name"
        type: "string"
    helmApiCertsMountPath:
      __metadata:
        label: "Helmapi Cert mount"
        description: "helmapi certs mount path"
        type: "string"
  env:
    DBHOST:
      __metadata:
        label: "Mongo host"
        description: "mongoDB host name"
        type: "string"
    DBPORT:
      __metadata:
        label: "Mongo port"
        description: "mongoDB port"
        type: "string"
    ISICP:
      __metadata:
        label: "Is ICP cluster"
        description: "Determines whether system is running as an ICP cluster"
        type: "boolean"
    MONGO_ISSSL: 
      __metadata:
        label: "Using SSL"
        description: "helmapi mongoDB use ssl"
        type: "boolean"
    MONGO_SSL_CA:
      __metadata:
        label: "MONGO SSL CA path"
        description: "helmapi mongoDB ssl CA path"
        type: "string"
    MONGO_SSL_CERT:
      __metadata:
        label: "Mongo SSL cert path"
        description: "helmapi mongoDB ssl cert path"
        type: "string"
    MONGO_SSL_KEY:
      __metadata:
        label: "Mongo SSL key path"
        description: "helmapi mongoDB ssl key path"
        type: "string"
    CLUSTER_PORT: 
      __metadata:
        label: "Cluster port"
        description: "Port number for cluster helmapi runs"
        type: "number"
    WLP_REDIRECT_URL:
      __metadata:
        label: "WLP redirect URL"
        description: "Redirect url for Liberty dynamic routing"
        type: "string"
    NO_PROXY:
      __metadata:
        label: "No proxy"
        description: "helmapi urls for no-proxy"
        type: "string"
    PROXY_EXTERNAL_ADDR:
      __metadata:
        label: "Proxy external address"
        description: "helmapi proxy external address for launch links"
        type: "string"
    CLUSTER_CA_DOMAIN: 
      __metadata:
        label: "Cluster CA domain"
        description: "cluster domain name"
        type: "string"
    SET_TLS:
      __metadata:
        label: "Set TLS"
        description: "helmapi set tls"
        type: "string"
    HTTPS_PROXY: 
      __metadata:
        label: "HTTPS proxy"
        description: "helmapi HTTPS proxy server"
        type: "string"
    HTTP_PROXY:
      __metadata:
        label: "HTTP proxy"
        description: "helmapi HTTP proxy server"
        type: "string"
    PROXY_ROUTE:
      __metadata:
        label: "Proxy route"
        description: "helmapi proxy route"
        type: "string"
    LOAD_ROUTES:
      __metadata:
        label: "Load routes"
        description: "helmapi load route"
        type: "string"
  secretKeyRef:
    dbSecretName:
      __metadata:
        label: "DB secret name"
        description: "helmapi secret name for mongoDB"
        type: "string"
    dbSecretUserKey:
      __metadata:
        label: "DB secret user key"
        description: "helmapi secret key for mongoDB user"
        type: "string"
    dbSecretPassKey:
      __metadata:
        label: "DB secret pass key"
        description: "helmapi secret key for mongoDB password"
        type: "string"
    clientIdSecretName:
      __metadata:
        label: "Client ID secret"
        description: "helmapi secret name for client id"
        type: "string"
    clientIdSecretKey:
      __metadata:
        label: "Client ID secretkey"
        description: "helmapi secret key for client id"
        type: "string"
    clientSecretSecretName:
      __metadata:
        label: "Client secret name"
        description: "helmapi secret name for client secret"
        type: "string"
    clientSecretSecretKey:
      __metadata:
        label: "Client secret key"
        description: "helmapi secret key for client secret"
        type: "string"
  service:
    name:
      __metadata:
        label: "Helmapi service name"
        description: "Name for the helmapi service"
        type: "string"
    portName:
      __metadata:
        label: "Helmapi service port name"
        description: "Name for the helmapi service port"
        type: "string"
    port:
      __metadata:
        label: "Helmapi service port"
        description: "helmapi service port number"
        type: "number"
  resources:
    limits:
      cpu:
        __metadata:
          label: "CPU limit"
          description: "CPU limit for helm api"
          type: "string"
          immutable: false
          required: false
      memory:
        __metadata:
          label: "Memory limit"
          description: "Memory limit for helm api"
          type: "string" 
          immutable: false
          required: false
    requests:
      cpu:
        __metadata:
          label: "Requested CPU"
          description: "Requested CPU amount for helm api"
          type: "string" 
          immutable: false
          required: false
          hidden: true
      memory: 
        __metadata:
          label: "Requested memory"
          description: "Requested memory for helm api"
          type: "string"
          immutable: false
          required: false
          hidden: true
  sharedassets:
    name:
      __metadata:
        label: "Shared assets"
        description: "Name for helmapi shared assets"
        type: "string"
    path:
      __metadata:
        label: "Shared assets path"
        description: "Path to helmapi's shared assets"
        type: "string"

rudder:
  __metadata:
    label: "Rudder component"
    description: "Bridge between helm API and Helm server"
  image:
    name:
      __metadata:
        label: "Image name"
        description: "Docker image name"
        type: "string"
        required: true
    repository:
      __metadata:
        label: "Repository"
        description: "Docker image location"
        type: "string"
        required: true
    tag:
      __metadata:
        label: "Tag"
        description: "Docker image tag"
        type: "string"
        required: false
    pullPolicy:
      __metadata:
        label: "Image pull policy"
        description: "Docker image pull policy"
        type: "string"
        required: true      
        options:
        - label: "Always"
          value: "Always"
        - label: "Never"
          value: "Never"
        - label: "IfNotPresent"
          value: "IfNotPresent"
  ports:
    containerPort:
      __metadata:
        label: "Rudder port"
        description: "Rudder container port number"
        type: "number"
    containerPortName:
      __metadata:
        label: "Rudder port name"
        description: "Rudder container port name"
        type: "string"
    protocol:
      __metadata:
        label: "Rudder port protocol"
        description: "Communication protocol for rudder container's port"
        type: "string"
  env:
    RUDDER_TILLER_ADDRESS:
      __metadata:
        label: "Rudder tiller address"
        description: "Address to reach tiller"
        type: "string"
    RUDDER_CLIENT_CERTS:
      __metadata:
        label: "Rudder client certs"
        description: "Certs with which Rudder can communicate with Tiller"
        type: "string"
    USE_TLS:
      __metadata:
        label: "Rudder use TLS"
        description: "Does rudder use TLS?"
        type: "string"
  volumeMounts:
    rudderCertsName:
      __metadata:
        label: "Rudder certs name"
        description: "Volume mount name for rudder certs"
        type: "string"
    rudderCertsMountPath:
      __metadata:
        label: "Rudder certs mount path"
        description: "Volume mount path for rudder certs"
        type: "string"
    rudderCacheName:
      __metadata:
        label: "Rudder cache name"
        description: "Volume mount name for Rudder's cache"
        type: "string"
    rudderCacheMountPath:
      __metadata:
        label: "Rudder cache mount path"
        description: "Volume mount path for Rudder's cache"
        type: "string"
  resources:
    limits:
      cpu:
        __metadata:
          label: "CPU limit"
          description: "CPU limit for rudder"
          type: "string"
          immutable: false
          required: false
      memory:
        __metadata:
          label: "Memory limit"
          description: "Memory limit for rudder"
          type: "string" 
          immutable: false
          required: false
    requests:
      cpu:
        __metadata:
          label: "Requested CPU"
          description: "Requested CPU amount for rudder"
          type: "string" 
          immutable: false
          required: false
          hidden: true
      memory: 
        __metadata:
          label: "Requested memory"
          description: "Requested memory for rudder"
          type: "string"
          immutable: false
          required: false
          hidden: true
  
volumes:
  __metadata:
    label: "Helmapi volumes"
    description: "Volumes for helm API and Mongo certs and secrets"
    hidden: true
  mongoClientCertName:
    __metadata:
      label: "Mongo cert name"
      description: "Mongo cert volume name"
      type: "string"
  mongoClientCertSecretName:
    __metadata:
      label: "Mongo cert secret name"
      description: "Mongo cert secret volume name"
      type: "string"
  mongoCaCertName:
    __metadata:
      label: "Mongo CA cert name"
      description: "Mongo CA cert volume name"
      type: "string"
  mongoCaCertSecretName:
    __metadata:
      label: "Mongo CA cert secret name"
      description: "Mongo CA cert secret volume name"
      type: "string"
  helmApiCertsName:
    __metadata:
      label: "Helmapi certs name"
      description: "Helmapi certs volume name"
      type: "string"
  helmApiCertsSecretName:
    __metadata:
      label: "Helmapi certs secret name"
      description: "Helmapi certs secret volume name"
      type: "string"
  rudderCertsName:
    __metadata:
      label: "Rudder certs name"
      description: "Rudder certs volume name"
      type: "string"
  rudderCertsSecretName:
    __metadata:
      label: "Rudder certs secret name"
      description: "Rudder certs secret volume name"
      type: "string"

auditService:
  __metadata:
    label: "Audit service"
    description: "Helm repo audit logging component"
  name:
    __metadata:
      label: "Service name"
      description: "Audit service component name"
      type: "string"
      required: true
  image:
    repository:
      __metadata:
        label: "Repository"
        description: "Docker image location"
        type: "string"
        required: true
    tag:
      __metadata:
        label: "Tag"
        description: "Docker image tag"
        type: "string"
        required: false
    pullPolicy:
      __metadata:
        label: "Image pull policy"
        description: "Docker image pull policy"
        type: "string"
        required: true      
        options:
        - label: "Always"
          value: "Always"
        - label: "Never"
          value: "Never"
        - label: "IfNotPresent"
          value: "IfNotPresent"

  config:
    enabled:
      __metadata:
        label: "Enable audit config"
        description: "Is audit config enabled?"
        type: "boolean"
